### ISSUE TITLE
[05-02 과제] 프로그래머스 힙, 백준 트리

### ISSUE THREAD

**Issue by chrisjo-dev** [ddusi/Algorithm_StudyGroup#24]
## 과제 
- [프로그래머스 힙 4문제](https://programmers.co.kr/learn/courses/30/parts/12117)
- [백준 트리 3문제](https://www.acmicpc.net/group/workbook/view/7974/22805)
    5639번, 1991번, 11725번
- 능력것 다른문제 10문제 이상 풀기.

**Comment by wayne-kyungwonpark** [comment]
힙 관련 문제 추천드립니다.
https://www.acmicpc.net/problem/1655

**Comment by chrisjo-dev** [comment]
오늘 다같이 이문제 풀어보면 좋겠네요!
